import React from "react";
import {
    SolarUsersGroupRoundedBold,
    SolarMicBold,
    SolarBook2Bold,
    SolarGalleryBold,
    SolarPenBold,
    SolarDocumentBold,
    SolarGraduationCapBold,
    SolarMedalRibbonsStarBold,
    SolarTrophyBold,
    SolarMusicNote2Bold,
    SolarAtomBold,
    SolarBriefcaseBold,
    SolarGlobeBold,
    SolarBookBold,
    SolarClipboardBold,
    SolarFlagBold,
    SolarBookmarkSquareBold,
    SolarBedBold,
    SolarCupHotBold,
    SolarDonutBold,
    SolarChefHatBold,
    SolarCandyBold,
    SolarDishBold,
    SolarClocheBold,
} from "@/components/icons/iconify";

export const iconsMap: Record<string, React.ReactElement> = {
    "solar:users-group-rounded-bold": <SolarUsersGroupRoundedBold />,
    "solar:mic-bold": <SolarMicBold />,
    "solar:book-2-bold": <SolarBook2Bold />,
    "solar:gallery-bold": <SolarGalleryBold />,
    "solar:pen-bold": <SolarPenBold />,
    "solar:document-bold": <SolarDocumentBold />,
    "solar:graduation-cap-bold": <SolarGraduationCapBold />,
    "solar:medal-ribbons-star-bold": <SolarMedalRibbonsStarBold />,
    "solar:trophy-bold": <SolarTrophyBold />,
    "solar:music-note-2-bold": <SolarMusicNote2Bold />,
    "solar:atom-bold": <SolarAtomBold />,
    "solar:briefcase-bold": <SolarBriefcaseBold />,
    "solar:globe-bold": <SolarGlobeBold />,
    "solar:book-bold": <SolarBookBold />,
    "solar:clipboard-bold": <SolarClipboardBold />,
    "solar:flag-bold": <SolarFlagBold />,
    "solar:bookmark-square-bold": <SolarBookmarkSquareBold />,
    "solar:bed-bold": <SolarBedBold />,
    "solar:cup-hot-bold": <SolarCupHotBold />,
    "solar:donut-bold": <SolarDonutBold />,
    "solar:chef-hat-bold": <SolarChefHatBold />,
    "solar:candy-bold": <SolarCandyBold />,
    "solar:dish-bold": <SolarDishBold />,
    "solar:cloche-bold": <SolarClocheBold />,
};
